# Generated by Django 4.2.9 on 2024-03-09 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0002_msg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='msg',
            old_name='chatname',
            new_name='room',
        ),
    ]
