# Generated by Django 4.2.9 on 2024-03-09 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatrooms', '0003_rename_chatname_msg_room'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='msg',
            options={'ordering': ('date_added',)},
        ),
        migrations.RenameField(
            model_name='msg',
            old_name='date',
            new_name='date_added',
        ),
        migrations.RemoveField(
            model_name='msg',
            name='username',
        ),
        migrations.AddField(
            model_name='msg',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='msg',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatrooms.chat'),
        ),
    ]
