# Generated by Django 4.2.9 on 2024-03-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0006_alter_chat_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='owner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
